# Generated by Django 6.0.5 on 2026-05-13 22:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_cards', models.PositiveIntegerField(default=360)),
                ('format_legality', models.CharField(blank=True, choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper')], max_length=32)),
                ('max_count_per_card', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cubes', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='cubes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('card_name', models.CharField(max_length=200)),
                ('scryfall_id', models.CharField(blank=True, max_length=64)),
                ('related_to', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cubes.cube')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('cube', 'player', 'round_number'), name='unique_submission_per_user_per_round')],
            },
        ),
    ]
