# Generated by Django 6.0.5 on 2026-05-25 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('round_ready', 'Round ready'), ('gentle_reminder', 'Gentle reminder')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='cubes.cube')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('cube', 'player', 'round_number', 'kind'), name='unique_notification_delivery_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('remind_after', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reminders', to='cubes.cube')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_after', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('cube', 'player', 'round_number'), name='unique_submission_reminder_per_round')],
            },
        ),
    ]
